/**
 * embed-assets determinism test.
 *
 * `src/cli/embedded-assets.ts` is a GENERATED file that is intentionally NOT
 * committed to git (it is .gitignore'd and regenerated by every consumer:
 * `bun run build:cli`, `scripts/release-build.mjs`, the npm `prepare` hook, and
 * the bunfig test preload). For that model to be safe, the generator MUST be
 * deterministic — two runs against an unchanged `targets/` tree must produce
 * byte-identical output. If it isn't, CI drift guards become meaningless and
 * the file churns on every regeneration.
 *
 * The historical nondeterminism source was a `Generated at: <ISO timestamp>`
 * line in the generated header (scripts/embed-assets.mjs). This test guards
 * against that (or any other nondeterminism) being (re)introduced.
 */

import { describe, expect, it } from "bun:test";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..", "..");
const OUTPUT = join(REPO_ROOT, "src", "cli", "embedded-assets.ts");

function generateOnce(): string {
  // Run the full `embed-assets` script (build:opencode + generator). The bare
  // generator requires the plugin bundle (targets/opencode/dist/sentinal.mjs),
  // which does not exist on a clean checkout — so `bun run embed-assets` builds
  // it first. It writes to src/cli/embedded-assets.ts; capture that content.
  execFileSync("bun", ["run", "embed-assets"], {
    cwd: REPO_ROOT,
    stdio: "ignore",
  });
  return readFileSync(OUTPUT, "utf-8");
}

describe("embed-assets generator determinism", () => {
  it("produces byte-identical output across two consecutive runs", () => {
    const first = generateOnce();
    const second = generateOnce();
    expect(second).toBe(first);
  }, 30_000);
});
