import { describe, expect, it } from "bun:test";
import { checkFileLength } from "./file-length";

describe("checkFileLength", () => {
  it("should return null for files under 400 lines", () => {
    const result = checkFileLength("/src/app.ts", 200);
    expect(result).toBeNull();
  });

  it("should return warn for files between 400-599 lines", () => {
    const result = checkFileLength("/src/app.ts", 450);
    expect(result).not.toBeNull();
    expect(result!.severity).toBe("warn");
    expect(result!.message).toContain("450 lines");
  });

  it("should return block for files at or above 600 lines", () => {
    const result = checkFileLength("/src/app.ts", 600);
    expect(result).not.toBeNull();
    expect(result!.severity).toBe("block");
    expect(result!.message).toContain("600 lines");
  });

  it("should exempt .spec.ts test files from blocking", () => {
    const result = checkFileLength("/src/app.spec.ts", 700);
    expect(result).toBeNull();
  });

  it("should exempt .test.ts files from blocking", () => {
    const result = checkFileLength("/src/app.test.ts", 700);
    expect(result).toBeNull();
  });

  it("should exempt e2e test files from blocking", () => {
    const result = checkFileLength("/e2e/app.e2e-spec.ts", 700);
    expect(result).toBeNull();
  });

  describe("auto-generated file detection", () => {
    it("should exempt files with AUTO-GENERATED marker in header", () => {
      const content = `/**
 * Embedded Assets — AUTO-GENERATED, DO NOT EDIT
 *
 * Generated by: node scripts/embed-assets.mjs
 */
export const X = "stuff";`;
      const result = checkFileLength(
        "/src/cli/embedded-assets.ts",
        11519,
        content,
      );
      expect(result).toBeNull();
    });

    it("should exempt files with @generated marker (JSDoc convention)", () => {
      const content = `/**
 * @generated by protobuf
 */
export const PB = {};`;
      const result = checkFileLength("/src/proto.ts", 900, content);
      expect(result).toBeNull();
    });

    it("should exempt files with DO NOT EDIT marker", () => {
      const content = `// DO NOT EDIT — this file is generated
export const foo = 1;`;
      const result = checkFileLength("/src/generated.ts", 800, content);
      expect(result).toBeNull();
    });

    it("should still block non-generated files even when content is provided", () => {
      const content = `// Regular hand-written file
export function doStuff() {
  return 42;
}`;
      const result = checkFileLength("/src/huge.ts", 700, content);
      expect(result).not.toBeNull();
      expect(result!.severity).toBe("block");
    });

    it("should only scan the first 500 characters for the marker", () => {
      // Marker appears after 500 chars — should NOT be exempt
      const padding = "x".repeat(600);
      const content = `// Regular file
${padding}
// AUTO-GENERATED should be ignored here
export const x = 1;`;
      const result = checkFileLength("/src/huge.ts", 700, content);
      expect(result).not.toBeNull();
      expect(result!.severity).toBe("block");
    });

    it("should work without content arg (backward compatible)", () => {
      const result = checkFileLength("/src/app.ts", 700);
      expect(result).not.toBeNull();
      expect(result!.severity).toBe("block");
    });
  });

  describe("PATH_EXEMPTIONS", () => {
    it("should return null for the OpenCode plugin sentinal.ts (relative path)", () => {
      const result = checkFileLength(
        "targets/opencode/plugins/sentinal.ts",
        1200,
      );
      expect(result).toBeNull();
    });

    it("should return null for the OpenCode plugin sentinal.ts (absolute path)", () => {
      const result = checkFileLength(
        "/absolute/path/targets/opencode/plugins/sentinal.ts",
        1200,
      );
      expect(result).toBeNull();
    });

    it("should still block other files over the limit", () => {
      const result = checkFileLength("src/some-other-file.ts", 1200);
      expect(result).not.toBeNull();
      expect(result!.severity).toBe("block");
    });
  });
});
