const WARN_THRESHOLD = 400;
const BLOCK_THRESHOLD = 600;
const GENERATED_HEADER_SCAN_BYTES = 500;
const TEST_PATTERNS = [
  /\.spec\.ts$/,
  /\.test\.ts$/,
  /\.e2e-spec\.ts$/,
  /\.spec\.js$/,
  /\.test\.js$/,
];

// Files exempt from length checks due to platform constraints.
// The OpenCode plugin must be a single file — its size is not actionable.
const PATH_EXEMPTIONS: ReadonlyArray<string> = [
  "targets/opencode/plugins/sentinal.ts",
];

// Markers that identify an auto-generated file. Case-insensitive.
// Only the first GENERATED_HEADER_SCAN_BYTES of the file are scanned to
// avoid false positives from legitimate code that mentions these phrases.
const GENERATED_MARKERS = [
  "AUTO-GENERATED",
  "AUTOGENERATED",
  "DO NOT EDIT",
  "@generated",
];

export interface FileLengthResult {
  severity: "warn" | "block";
  message: string;
}

/**
 * Returns true if the first ~500 bytes of `content` contain a recognised
 * auto-generated file marker. Common conventions:
 *   - `AUTO-GENERATED` (sentinal's own scripts/embed-assets.mjs output)
 *   - `DO NOT EDIT`    (widely used across tooling)
 *   - `@generated`     (JSDoc / protobuf / GraphQL codegen convention)
 */
function isGeneratedFile(content: string): boolean {
  const header = content.slice(0, GENERATED_HEADER_SCAN_BYTES).toUpperCase();
  return GENERATED_MARKERS.some((marker) =>
    header.includes(marker.toUpperCase()),
  );
}

export function checkFileLength(
  filePath: string,
  lineCount: number,
  content?: string,
): FileLengthResult | null {
  if (PATH_EXEMPTIONS.some((exempt) => filePath.endsWith(exempt))) {
    return null;
  }

  if (TEST_PATTERNS.some((p) => p.test(filePath))) {
    return null;
  }

  if (content !== undefined && isGeneratedFile(content)) {
    return null;
  }

  if (lineCount >= BLOCK_THRESHOLD) {
    return {
      severity: "block",
      message: `File is ${lineCount} lines (limit: ${BLOCK_THRESHOLD}). Refactor into smaller modules before continuing.`,
    };
  }

  if (lineCount >= WARN_THRESHOLD) {
    return {
      severity: "warn",
      message: `File is ${lineCount} lines (soft limit: ${WARN_THRESHOLD}). Consider splitting into smaller modules.`,
    };
  }

  return null;
}
