/**
 * Transformers Bundle Builder
 *
 * Compiled sentinal binaries cannot resolve node_modules for external
 * modules' bare imports, so `@xenova/transformers` (installed into
 * ~/.sentinal/deps by `sentinal memory setup`) fails to load there.
 *
 * Fix (spike-proven 2026-06-10): flatten transformers into ONE self-contained
 * ESM file whose only remaining bare imports are Node builtins — those DO
 * resolve in compiled binaries. Two bundler paths:
 *
 *   1. system `bun` running a Bun.build script (sharp stubbed via plugin)
 *   2. `npx esbuild` CLI (--alias:sharp=<stub> --external:*.node + banner)
 *
 * Both rely on the native onnxruntime layout: the bundle lives at
 * <deps>/bundle/transformers.bundle.mjs and requires
 * ../bin/napi-v3/<platform>/<arch>/onnxruntime_binding.node, so
 * onnxruntime-node's bin tree is copied to <deps>/bin.
 */

import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { BUNDLE_REL_PATH, DEPS_DIR } from "./native-deps.js";

// ─── Constants ────────────────────────────────────────────────────────────────

export { BUNDLE_REL_PATH };
export const BUNDLE_META_REL_PATH = join("bundle", ".bundle-meta.json");

const ESBUILD_BANNER =
  "import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);";

/** Bun.build script template — written to the deps dir and spawned via bun. */
const BUN_BUILD_SCRIPT = `// Generated by sentinal memory setup — do not edit
const [depsDir, outFile] = process.argv.slice(2);
const result = await Bun.build({
  entrypoints: [\`\${depsDir}/node_modules/@xenova/transformers/src/transformers.js\`],
  target: "node",
  format: "esm",
  plugins: [
    {
      name: "stub-sharp",
      setup(build) {
        build.onResolve({ filter: /^sharp$/ }, () => ({
          path: "sharp-stub",
          namespace: "stub",
        }));
        build.onLoad({ filter: /.*/, namespace: "stub" }, () => ({
          contents: "export default null;",
          loader: "js",
        }));
      },
    },
  ],
});
if (!result.success) {
  console.error(result.logs.join("\\n"));
  process.exit(1);
}
await Bun.write(outFile, await result.outputs[0].text());
`;

// ─── Types ────────────────────────────────────────────────────────────────────

export interface BundleBuildOptions {
  depsDir?: string;
  /**
   * Spawns a command synchronously; returns its exit code, throws on spawn
   * failure. Injectable for tests; default uses child_process.spawnSync.
   */
  spawner?: (cmd: string[], opts?: { cwd?: string }) => number;
  /** Skip the post-build import smoke (unit tests with fake bundles). */
  skipSmoke?: boolean;
}

export interface BundleBuildResult {
  ok: boolean;
  bundler: "bun" | "esbuild" | null;
  report: string[];
}

interface BundleMeta {
  transformersVersion: string;
  builtAt: number;
  bundler: "bun" | "esbuild";
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function defaultSpawner(cmd: string[], opts?: { cwd?: string }): number {
  const { spawnSync } = require("node:child_process") as {
    spawnSync: (
      command: string,
      args: string[],
      options: { stdio: "inherit"; cwd?: string },
    ) => { status: number | null; error?: Error };
  };
  const result = spawnSync(cmd[0]!, cmd.slice(1), {
    stdio: "inherit",
    cwd: opts?.cwd,
  });
  if (result.error) throw result.error;
  return result.status ?? 1;
}

function installedTransformersVersion(depsDir: string): string | null {
  try {
    const pkg = JSON.parse(
      readFileSync(
        join(
          depsDir,
          "node_modules",
          "@xenova",
          "transformers",
          "package.json",
        ),
        "utf-8",
      ),
    ) as { version?: string };
    return pkg.version ?? null;
  } catch {
    return null;
  }
}

// ─── Freshness ────────────────────────────────────────────────────────────────

/**
 * True when a bundle exists and was built from the currently-installed
 * transformers version. Version comparison (not mtime) so an old binary
 * provisioning old versions never wedges freshness (Pre-Mortem #2).
 */
export function isBundleFresh(depsDir: string = DEPS_DIR): boolean {
  const bundlePath = join(depsDir, BUNDLE_REL_PATH);
  const metaPath = join(depsDir, BUNDLE_META_REL_PATH);
  if (!existsSync(bundlePath) || !existsSync(metaPath)) return false;
  try {
    const meta = JSON.parse(readFileSync(metaPath, "utf-8")) as BundleMeta;
    const installed = installedTransformersVersion(depsDir);
    return installed !== null && meta.transformersVersion === installed;
  } catch {
    return false;
  }
}

// ─── Build ────────────────────────────────────────────────────────────────────

/**
 * Build the self-contained transformers bundle. Tries bun first (Bun.build
 * script with the sharp stub plugin), falls back to `npx esbuild`. Copies
 * the onnxruntime-node native bin tree alongside and writes freshness meta.
 */
export async function buildTransformersBundle(
  opts: BundleBuildOptions = {},
): Promise<BundleBuildResult> {
  const depsDir = opts.depsDir ?? DEPS_DIR;
  const spawner = opts.spawner ?? defaultSpawner;
  const report: string[] = [];

  const entry = join(
    depsDir,
    "node_modules",
    "@xenova",
    "transformers",
    "src",
    "transformers.js",
  );
  const version = installedTransformersVersion(depsDir);
  if (!existsSync(entry) || version === null) {
    report.push(
      "Cannot bundle: @xenova/transformers is not installed in the deps dir.",
    );
    return { ok: false, bundler: null, report };
  }

  const bundlePath = join(depsDir, BUNDLE_REL_PATH);
  mkdirSync(join(depsDir, "bundle"), { recursive: true });

  // 1. Bundle (bun → esbuild)
  let bundler: "bun" | "esbuild" | null = null;
  const buildScript = join(depsDir, ".build-bundle.ts");
  writeFileSync(buildScript, BUN_BUILD_SCRIPT);
  try {
    const code = spawner(["bun", buildScript, depsDir, bundlePath]);
    if (code === 0 && existsSync(bundlePath)) bundler = "bun";
    else report.push(`bun bundle exited with code ${code}`);
  } catch (e) {
    report.push(`bun unavailable for bundling: ${(e as Error).message}`);
  }

  if (!bundler) {
    const stubPath = join(depsDir, ".sharp-stub.js");
    writeFileSync(stubPath, "export default null;\n");
    try {
      const code = spawner([
        "npx",
        "-y",
        "esbuild",
        entry,
        "--bundle",
        "--format=esm",
        "--platform=node",
        `--alias:sharp=${stubPath}`,
        "--external:*.node",
        `--banner:js=${ESBUILD_BANNER}`,
        `--outfile=${bundlePath}`,
      ]);
      if (code === 0 && existsSync(bundlePath)) bundler = "esbuild";
      else report.push(`esbuild bundle exited with code ${code}`);
    } catch (e) {
      report.push(`esbuild unavailable for bundling: ${(e as Error).message}`);
    }
  }

  if (!bundler) {
    report.push(
      "Bundling failed — semantic search needs bun (preferred) or npx on PATH.",
    );
    return { ok: false, bundler: null, report };
  }
  report.push(`Bundled @xenova/transformers ${version} via ${bundler}.`);

  // 2. Native onnxruntime layout: <deps>/bin sibling of <deps>/bundle
  const binSrc = join(depsDir, "node_modules", "onnxruntime-node", "bin");
  if (existsSync(binSrc)) {
    cpSync(binSrc, join(depsDir, "bin"), { recursive: true });
    report.push("Copied onnxruntime native binaries to deps/bin.");
  } else {
    report.push(
      "Warning: onnxruntime-node/bin not found — native backend may be unavailable.",
    );
  }

  // 3. Import smoke BEFORE freshness meta — a bundle that fails its smoke
  // must not be recorded as fresh (it would mask a broken artifact until
  // the compiled binary's single self-heal attempt rebuilds the same thing).
  // "Cannot run the smoke" (no bun) is non-fatal; "smoke ran and failed" is.
  if (!opts.skipSmoke) {
    try {
      const code = spawner([
        "bun",
        "-e",
        `import("${bundlePath.replaceAll("\\", "/")}").then((m) => process.exit(m.pipeline ? 0 : 1)).catch(() => process.exit(1));`,
      ]);
      if (code !== 0) {
        report.push(`Bundle import smoke failed (exit ${code}) — not recording the bundle as usable.`);
        return { ok: false, bundler, report };
      }
      report.push("Bundle import smoke passed.");
    } catch {
      report.push("Bundle import smoke skipped (bun not available).");
    }
  }

  // 4. Freshness meta — only after the bundle proved importable (or the
  // smoke was skipped/unavailable).
  const meta: BundleMeta = {
    transformersVersion: version,
    builtAt: Date.now(),
    bundler,
  };
  writeFileSync(join(depsDir, BUNDLE_META_REL_PATH), JSON.stringify(meta));

  return { ok: true, bundler, report };
}
