#!/usr/bin/env node

/**
 * Embed Assets Script
 *
 * Reads all OpenCode and Claude Code plugin assets and generates
 * src/cli/embedded-assets.ts with their contents as exported string constants.
 *
 * This file MUST be regenerated before compiling the CLI binary so that the
 * latest assets are baked into the executable.
 *
 * Usage: node scripts/embed-assets.mjs
 * Also: bun run embed-assets
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";

// ── Paths ──

const OPENCODE_DIR = "targets/opencode";
const CLAUDE_DIR = "targets/claude-code";
const PLUGIN_BUNDLE = join(OPENCODE_DIR, "dist", "sentinal.mjs");
const OUTPUT = "src/cli/embedded-assets.ts";

// ── Helpers ──

function readDir(dir, ext = ".md") {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(ext))
    .sort()
    .map((f) => ({ name: f, content: readFileSync(join(dir, f), "utf-8") }));
}

function readFile(path) {
  if (!existsSync(path)) return null;
  return readFileSync(path, "utf-8");
}

/** Read skill directories: skills/<name>/SKILL.md → [{ name: "<name>/SKILL.md", content }] */
function readSkillDirs(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((d) => existsSync(join(dir, d, "SKILL.md")))
    .sort()
    .map((d) => ({ name: `${d}/SKILL.md`, content: readFileSync(join(dir, d, "SKILL.md"), "utf-8") }));
}

function escapeForTemplate(s) {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function emitRecord(lines, varName, entries) {
  lines.push(`export const ${varName}: Record<string, string> = {`);
  for (const entry of entries) {
    lines.push(`  ${JSON.stringify(entry.name)}: \`${escapeForTemplate(entry.content)}\`,`);
  }
  lines.push("};");
  lines.push("");
}

function emitString(lines, varName, content) {
  lines.push(`export const ${varName} = \`${escapeForTemplate(content)}\`;`);
  lines.push("");
}

// ── Read OpenCode assets ──

if (!existsSync(PLUGIN_BUNDLE)) {
  console.error(`Plugin bundle not found: ${PLUGIN_BUNDLE}`);
  console.error("Run 'bun run build:opencode' first.");
  process.exit(1);
}

const pluginContent = readFileSync(PLUGIN_BUNDLE, "utf-8");
const ocCommands = readDir(join(OPENCODE_DIR, "commands"));
const ocRules = readDir(join(OPENCODE_DIR, "rules"));
const ocAgents = readDir(join(OPENCODE_DIR, "agents"));
const ocSkills = readSkillDirs(join(OPENCODE_DIR, "skills"));
const ocConfigJson = readFile(join(OPENCODE_DIR, "opencode.json"));

console.log("── OpenCode ──");
console.log(`  Plugin bundle: ${(pluginContent.length / 1024).toFixed(1)} KB`);
console.log(`  Commands: ${ocCommands.map((c) => c.name).join(", ")}`);
console.log(`  Rules: ${ocRules.map((r) => r.name).join(", ")}`);
console.log(`  Agents: ${ocAgents.map((a) => a.name).join(", ") || "(none)"}`);
console.log(`  Skills: ${ocSkills.map((s) => s.name).join(", ") || "(none)"}`);
console.log(`  Config: ${ocConfigJson ? "OK" : "MISSING"}`);

// ── Read Claude Code assets ──

console.log("\n── Claude Code ──");

const ccPluginJson = readFile(join(CLAUDE_DIR, ".claude-plugin", "plugin.json"));
const ccLspJson = readFile(join(CLAUDE_DIR, ".lsp.json"));
const ccMcpJson = readFile(join(CLAUDE_DIR, ".mcp.json"));
const ccSettingsJson = readFile(join(CLAUDE_DIR, "settings.json"));
const ccHooksJson = readFile(join(CLAUDE_DIR, "hooks", "hooks.json"));
const ccAgents = readDir(join(CLAUDE_DIR, "agents"));
const ccCommands = readDir(join(CLAUDE_DIR, "commands"));
const ccRules = readDir(join(CLAUDE_DIR, "rules"));

const ccConfigFiles = [
  { label: "plugin.json", val: ccPluginJson },
  { label: ".lsp.json", val: ccLspJson },
  { label: ".mcp.json", val: ccMcpJson },
  { label: "settings.json", val: ccSettingsJson },
  { label: "hooks.json", val: ccHooksJson },
];

for (const { label, val } of ccConfigFiles) {
  console.log(`  ${val ? "OK" : "MISSING"}: ${label}`);
}
console.log(`  Agents: ${ccAgents.map((a) => a.name).join(", ") || "(none)"}`);
console.log(`  Commands: ${ccCommands.map((c) => c.name).join(", ") || "(none)"}`);
console.log(`  Rules: ${ccRules.map((r) => r.name).join(", ") || "(none)"}`);

const missingConfigs = ccConfigFiles.filter((c) => !c.val);
if (missingConfigs.length > 0) {
  console.error(`\nERROR: Missing Claude Code config files: ${missingConfigs.map((c) => c.label).join(", ")}`);
  process.exit(1);
}

// ── Generate TypeScript ──

const lines = [
  "/**",
  " * Embedded Assets — AUTO-GENERATED, DO NOT EDIT",
  " *",
  " * Generated by: node scripts/embed-assets.mjs",
  ` * Generated at: ${new Date().toISOString()}`,
  " *",
  " * Contains all OpenCode and Claude Code plugin assets as string constants",
  " * for use in compiled binary mode where the source tree is not available.",
  " */",
  "",
  "// ═══════════════════════════════════════════════════════════════════════════════",
  "// OpenCode Assets",
  "// ═══════════════════════════════════════════════════════════════════════════════",
  "",
  "// ─── Plugin bundle ───────────────────────────────────────────────────────────",
  "",
];

emitString(lines, "EMBEDDED_OPENCODE_PLUGIN", pluginContent);

lines.push("// ─── OpenCode Commands ───────────────────────────────────────────────────────");
lines.push("");
emitRecord(lines, "EMBEDDED_COMMANDS", ocCommands);

lines.push("// ─── OpenCode Rules ─────────────────────────────────────────────────────────");
lines.push("");
emitRecord(lines, "EMBEDDED_RULES", ocRules);

lines.push("// ─── OpenCode Agents ────────────────────────────────────────────────────────");
lines.push("");
emitRecord(lines, "EMBEDDED_OC_AGENTS", ocAgents);

lines.push("// ─── OpenCode Skills ────────────────────────────────────────────────────────");
lines.push("");
emitRecord(lines, "EMBEDDED_OC_SKILLS", ocSkills);

lines.push("// ─── OpenCode Config Template ───────────────────────────────────────────────");
lines.push("");
if (ocConfigJson) {
  emitString(lines, "EMBEDDED_OC_CONFIG_JSON", ocConfigJson);
}

lines.push("// ═══════════════════════════════════════════════════════════════════════════════");
lines.push("// Claude Code Assets");
lines.push("// ═══════════════════════════════════════════════════════════════════════════════");
lines.push("");

// Config files
lines.push("// ─── Claude Code Config Files ────────────────────────────────────────────────");
lines.push("");
emitString(lines, "EMBEDDED_CC_PLUGIN_JSON", ccPluginJson);
emitString(lines, "EMBEDDED_CC_LSP_JSON", ccLspJson);
emitString(lines, "EMBEDDED_CC_MCP_JSON", ccMcpJson);
emitString(lines, "EMBEDDED_CC_SETTINGS_JSON", ccSettingsJson);
emitString(lines, "EMBEDDED_CC_HOOKS_JSON", ccHooksJson);

// Agents
lines.push("// ─── Claude Code Agents ──────────────────────────────────────────────────────");
lines.push("");
emitRecord(lines, "EMBEDDED_CC_AGENTS", ccAgents);

// Commands
lines.push("// ─── Claude Code Commands ────────────────────────────────────────────────────");
lines.push("");
emitRecord(lines, "EMBEDDED_CC_COMMANDS", ccCommands);

// Rules
lines.push("// ─── Claude Code Rules ───────────────────────────────────────────────────────");
lines.push("");
emitRecord(lines, "EMBEDDED_CC_RULES", ccRules);

writeFileSync(OUTPUT, lines.join("\n"));
console.log(`\nGenerated: ${OUTPUT} (${lines.length} lines)`);
