/**
 * Completion Command
 *
 * `sentinal completion bash|zsh|fish` — Output shell completion script to stdout.
 *
 * Usage:
 *   eval "$(sentinal completion bash)"   # Bash
 *   eval "$(sentinal completion zsh)"    # Zsh
 *   sentinal completion fish | source    # Fish
 */

import type { Command } from "commander";

// ─── Command list ────────────────────────────────────────────────────────────
// Maintained manually — update when adding new CLI commands.

interface SubcommandInfo {
  name: string;
  description: string;
  options?: string[];
}

const SUBCOMMANDS: SubcommandInfo[] = [
  { name: "mcp-server", description: "Start the Sentinal MCP server (stdio)" },
  {
    name: "memory",
    description: "Memory CLI — search, list, get, stats, prune, repair, export",
  },
  { name: "greet", description: "Display the Sentinal banner" },
  {
    name: "spec",
    description: "Spec workflow — list, current, sync plan files",
  },
  { name: "config", description: "Manage settings — list, get, set, reset" },
  { name: "sessions", description: "Manage sessions — list, cleanup stale" },
  {
    name: "check-context",
    description: "Estimate context window usage",
    options: ["--json", "--transcript-path"],
  },
  {
    name: "register-plan",
    description: "Register a plan file in SQLite",
    options: ["--project"],
  },
  { name: "worktree", description: "Git worktree management" },
  {
    name: "serve",
    description: "Start the console dashboard server",
    options: ["--port", "--host", "--background"],
  },
  {
    name: "install",
    description: "Install Sentinal for an AI assistant",
    options: ["--local"],
  },
  {
    name: "uninstall",
    description: "Uninstall Sentinal from an AI assistant",
    options: ["--local"],
  },
  {
    name: "update",
    description: "Check for and install updates",
    options: ["--check"],
  },
  {
    name: "shell-init",
    description: "Set up shell aliases, PATH, and completions",
    options: ["--dry-run", "--shell"],
  },
  { name: "completion", description: "Output shell completion script" },
  { name: "help", description: "Display help for command" },
];

const GLOBAL_OPTIONS = ["--version", "--help", "--skip-update-check"];

// ─── Generators ──────────────────────────────────────────────────────────────

export function generateBashCompletion(): string {
  const cmdNames = SUBCOMMANDS.map((c) => c.name).join(" ");
  const optionCases = SUBCOMMANDS.filter((c) => c.options?.length)
    .map(
      (c) =>
        `      ${c.name})\n        COMPREPLY=( $(compgen -W "${c.options!.join(" ")}" -- "$cur") )\n        return 0\n        ;;`,
    )
    .join("\n");

  return `# sentinal bash completion — generated by sentinal completion bash
_sentinal_completions() {
  local cur prev commands
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  commands="${cmdNames}"

  if [[ \${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "\${commands} ${GLOBAL_OPTIONS.join(" ")}" -- "$cur") )
    return 0
  fi

  case "\${COMP_WORDS[1]}" in
${optionCases}
      completion)
        COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
        return 0
        ;;
      install|uninstall)
        if [[ \${COMP_CWORD} -eq 2 ]]; then
          COMPREPLY=( $(compgen -W "claude opencode both" -- "$cur") )
        fi
        return 0
        ;;
  esac
}
complete -F _sentinal_completions sentinal
complete -F _sentinal_completions snt
`;
}

export function generateZshCompletion(): string {
  const cmdDescriptions = SUBCOMMANDS.map(
    (c) => `    '${c.name}:${c.description.replace(/'/g, "'\\''")}'`,
  ).join("\n");

  const optionCases = SUBCOMMANDS.filter((c) => c.options?.length)
    .map((c) => {
      const opts = c.options!.map((o) => `'${o}[${c.description}]'`).join(" ");
      return `    ${c.name})\n      _arguments ${opts}\n      ;;`;
    })
    .join("\n");

  return `#compdef sentinal snt
# sentinal zsh completion — generated by sentinal completion zsh
_sentinal() {
  local -a commands
  commands=(
${cmdDescriptions}
  )

  _arguments -C \\
    '1:command:->cmds' \\
    '*::arg:->args'

  case "$state" in
    cmds)
      _describe -t commands 'sentinal command' commands
      ;;
    args)
      case "\${words[1]}" in
${optionCases}
        completion)
          _values 'shell' bash zsh fish
          ;;
        install|uninstall)
          _values 'target' claude opencode both
          ;;
      esac
      ;;
  esac
}
_sentinal "$@"
`;
}

export function generateFishCompletion(): string {
  const lines = [
    "# sentinal fish completion — generated by sentinal completion fish",
    "# Disable file completions for sentinal",
    "complete -c sentinal -f",
    "complete -c snt -f",
    "",
  ];

  // Global options
  for (const opt of GLOBAL_OPTIONS) {
    const long = opt.replace(/^--/, "");
    lines.push(`complete -c sentinal -l ${long} -d 'Global option'`);
    lines.push(`complete -c snt -l ${long} -d 'Global option'`);
  }
  lines.push("");

  // Subcommands
  for (const cmd of SUBCOMMANDS) {
    const desc = cmd.description.replace(/'/g, "\\'");
    lines.push(
      `complete -c sentinal -n '__fish_use_subcommand' -a '${cmd.name}' -d '${desc}'`,
    );
    lines.push(
      `complete -c snt -n '__fish_use_subcommand' -a '${cmd.name}' -d '${desc}'`,
    );

    // Sub-command options
    if (cmd.options) {
      for (const opt of cmd.options) {
        const long = opt.replace(/^--/, "");
        lines.push(
          `complete -c sentinal -n '__fish_seen_subcommand_from ${cmd.name}' -l ${long}`,
        );
        lines.push(
          `complete -c snt -n '__fish_seen_subcommand_from ${cmd.name}' -l ${long}`,
        );
      }
    }
  }

  // Special: completion subcommand accepts shell names
  lines.push("");
  lines.push(
    "complete -c sentinal -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'",
  );
  lines.push(
    "complete -c snt -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'",
  );

  // Special: install/uninstall accept target names
  lines.push(
    "complete -c sentinal -n '__fish_seen_subcommand_from install' -a 'claude opencode both'",
  );
  lines.push(
    "complete -c snt -n '__fish_seen_subcommand_from install' -a 'claude opencode both'",
  );
  lines.push(
    "complete -c sentinal -n '__fish_seen_subcommand_from uninstall' -a 'claude opencode both'",
  );
  lines.push(
    "complete -c snt -n '__fish_seen_subcommand_from uninstall' -a 'claude opencode both'",
  );

  return lines.join("\n") + "\n";
}

// ─── Register command ────────────────────────────────────────────────────────

export function registerCompletionCommand(program: Command): void {
  program
    .command("completion [shell]")
    .description("Output shell completion script (bash, zsh, fish)")
    .action((shell?: string) => {
      const detectedShell = shell ?? detectShellType();

      switch (detectedShell) {
        case "bash":
          process.stdout.write(generateBashCompletion());
          break;
        case "zsh":
          process.stdout.write(generateZshCompletion());
          break;
        case "fish":
          process.stdout.write(generateFishCompletion());
          break;
        default:
          console.error(
            `Unknown shell: ${detectedShell ?? "(none)"}. Supported: bash, zsh, fish`,
          );
          process.exit(1);
      }
    });
}

/** Detect shell type from $SHELL env var. */
function detectShellType(): string | undefined {
  const shell = process.env.SHELL ?? "";
  if (shell.includes("zsh")) return "zsh";
  if (shell.includes("bash")) return "bash";
  if (shell.includes("fish")) return "fish";
  return undefined;
}
